### ISSUE TITLE
Plugin crashes on running "terraform destroy -auto-approve"

### ISSUE THREAD

**Issue by sauhrub** [terraform-aws-modules/terraform-aws-eks#1598]
# I have issues

Unable to run `terraform destroy -auto-approve`

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

Few resources have their states refreshed and then I see the below error:

```
Stack trace from the terraform-provider-aws_v3.59.0_x5 plugin:

panic: interface conversion: interface {} is nil, not *aws.AWSClient

goroutine 45 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsEksNodeGroupRead(0x8d246d8, 0xc000ce3080, 0xc00200a700, 0x0, 0x0, 0xc0023d79a0, 0xc00232b908, 0x100df38)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_eks_node_group.go:374 +0x201f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000a057a0, 0x8d24668, 0xc000ce8980, 0xc00200a700, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/resource.go:347 +0x17f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000a057a0, 0x8d24668, 0xc000ce8980, 0xc0023ce150, 0x0, 0x0, 0xc000cf4720, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000c828, 0x8d24668, 0xc000ce8980, 0xc000ce89c0, 0xc000ce8980, 0x100b665, 0x7c3b600)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc00080c060, 0x8d24710, 0xc000ce8980, 0xc000ce28a0, 0xc00080c060, 0xc0023c25d0, 0xc000cdcba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x7f29aa0, 0xc00080c060, 0x8d24710, 0xc0023c25d0, 0xc000ce2840, 0x0, 0x8d24710, 0xc0023c25d0, 0xc0023b4500, 0x4e4)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001ff6c0, 0x8d47058, 0xc001086a80, 0xc0023ae300, 0xc0012ab1a0, 0xc6fb910, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0001ff6c0, 0x8d47058, 0xc001086a80, 0xc0023ae300, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000625980, 0xc0001ff6c0, 0x8d47058, 0xc001086a80, 0xc0023ae300)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.59.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

## If this is a bug, how to reproduce? Please include a code sample if relevant.

Follow the guide on the below link:
https://github.com/antonputra/tutorials/tree/main/lessons/006

## What's the expected behavior?

`terraform destroy -auto-approve` should run successfully

## Are you able to fix this problem and submit a PR? Link here if you have already.

No

## Environment details

* Affected module version: terraform-provider-aws_v3.59.0_x5
* OS: macOS 11.2.3 (darwin_amd64)
* Terraform version: Terraform v1.0.5

**Comment by antonbabenko** [comment]
It is a bug in the provider, so please open this issue in [Terraform AWS provider repository](https://github.com/hashicorp/terraform-provider-aws/issues) and include the error log.
