### ISSUE TITLE
Error: The terraform-provider-aws_v3.65.0_x5 plugin crashed! Module EKS

### ISSUE THREAD

**Issue by vekonyz** [terraform-aws-modules/terraform-aws-eks#1706]
## Description

Error: The terraform-provider-aws_v3.65.0_x5 plugin crashed! during terraform destroy

```
module.eks.module.node_groups.aws_eks_node_group.workers["worker"] (deposed object 04748b93): Refreshing state... [id=xxxxx:yyyyyy-worker20211126144915243700000001]
╷
│ Error: Plugin did not respond
│
│   with module.eks.aws_launch_configuration.workers[0],
│   on .terraform/modules/eks/workers.tf line 204, in resource "aws_launch_configuration" "workers":
│  204: resource "aws_launch_configuration" "workers" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.eks.module.node_groups.aws_eks_node_group.workers["worker"],
│   on .terraform/modules/eks/modules/node_groups/main.tf line 1, in resource "aws_eks_node_group" "workers":
│    1: resource "aws_eks_node_group" "workers" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-aws_v3.65.0_x5 plugin:

panic: interface conversion: interface {} is nil, not *conns.AWSClient

goroutine 61 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/eks.resourceNodeGroupRead(0x9eab7b8, 0xc00057e360, 0xc00244c380, 0x0, 0x0, 0xc00056d7d0, 0xc003131908, 0x40e0f8)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/eks/node_group.go:374 +0x201f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc00139efc0, 0x9eab748, 0xc0005661c0, 0xc00244c380, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/resource.go:347 +0x17f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00139efc0, 0x9eab748, 0xc0005661c0, 0xc00310e310, 0x0, 0x0, 0xc000572370, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000c5b8, 0x9eab748, 0xc0005661c0, 0xc000566200, 0xc0005661c0, 0x40b965, 0x894e160)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc0023d5f60, 0x9eab7f0, 0xc0005661c0, 0xc00057e240, 0xc0023d5f60, 0xc0005689f0, 0xc003575ba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x8d0bac0, 0xc0023d5f60, 0x9eab7f0, 0xc0005689f0, 0xc00057e1e0, 0x0, 0x9eab7f0, 0xc0005689f0, 0xc00311a000, 0x672)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000243500, 0x9ed6558, 0xc001c8c900, 0xc003118000, 0xc0020609c0, 0xe76f810, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000243500, 0x9ed6558, 0xc001c8c900, 0xc003118000, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc001a3b000, 0xc000243500, 0x9ed6558, 0xc001c8c900, 0xc003118000)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.65.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions
 - Terraform:
$ ~/bin/terraform -v
Terraform v1.0.5
on linux_amd64
 - Provider(s):
+ provider registry.terraform.io/hashicorp/aws v3.65.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.6.1
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1
 - Module:
 -  aws.eks

## Reproduction

 default
 no
 
- cluster created
- but nodes could not be connected to the cluster -> "Instances failed to join the kubernetes cluster"
- cluster destroyed -> terraform crashed immediately

## Expected behavior
 EKS cluster will be destroyed without error / crash

## Actual behavior
 crash

### Terminal Output Screenshot(s)
 see above

**Comment by daroga0002** [comment]
there is nothing we can do here as module maintainers, please report this issue to https://github.com/hashicorp/terraform-provider-aws

**Comment by daroga0002** [comment]
also newest version of provider is `v3.67.0` 

https://github.com/hashicorp/terraform-provider-aws/releases


closing this issue as this is not related to module itself and I was not able to replicate problem on newest provider
