### ISSUE TITLE
Node security group is insufficient for EMR on EKS

### ISSUE THREAD

**Issue by jaehyeon-kim** [terraform-aws-modules/terraform-aws-eks#1778]
## Is your request related to a new offering from AWS?

It's available. Specifically https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/node_groups.tf#L21

## Is your request related to a problem? Please describe.

Insufficient security group rules (both inbound/outbound) so that spark executors fails to connect to the spark driver.

**executor log**
```
2022-01-14T00:53:51.332+0000: [GC (CMS Final Remark) [YG occupancy: 234567 K (306688 K)]2022-01-14T00:53:51.332+0000: [Rescan (parallel) , 0.0428936 secs]2022-01-14T00:53:51.375+0000: [weak refs processing, 0.0000496 secs]2022-01-14T00:53:51.375+0000: [class unloading, 0.0032346 secs]2022-01-14T00:53:51.378+0000: [scrub symbol table, 0.0020016 secs]2022-01-14T00:53:51.380+0000: [scrub string table, 0.0003772 secs][1 CMS-remark: 0K(1756416K)] 234567K(2063104K), 0.0490921 secs] [Times: user=0.17 sys=0.00, real=0.05 secs] 
2022-01-14T00:53:51.381+0000: [CMS-concurrent-sweep-start]
2022-01-14T00:53:51.381+0000: [CMS-concurrent-sweep: 0.000/0.000 secs] [Times: user=0.00 sys=0.00, real=0.00 secs] 
2022-01-14T00:53:51.381+0000: [CMS-concurrent-reset-start]
2022-01-14T00:53:51.400+0000: [CMS-concurrent-reset: 0.019/0.019 secs] [Times: user=0.00 sys=0.02, real=0.02 secs] 
22/01/14 00:55:44 ERROR RpcOutboxMessage: Ask terminated before connecting successfully
22/01/14 00:55:44 WARN NettyRpcEnv: Ignored failure: java.io.IOException: Connecting to spark-00000002vim192ao4dv-06b24e7e560b1279-driver-svc.spark.svc/10.99.80.100:7078 timed out (120000 ms)
Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1748)
	at org.apache.spark.deploy.SparkHadoopUtil.runAsSparkUser(SparkHadoopUtil.scala:61)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.run(CoarseGrainedExecutorBackend.scala:457)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.main(CoarseGrainedExecutorBackend.scala:446)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend.main(CoarseGrainedExecutorBackend.scala)
Caused by: org.apache.spark.rpc.RpcTimeoutException: Futures timed out after [120 seconds]. This timeout is controlled by spark.rpc.lookupTimeout
	at org.apache.spark.rpc.RpcTimeout.org$apache$spark$rpc$RpcTimeout$$createRpcTimeoutException(RpcTimeout.scala:47)
	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:62)
	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:58)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:76)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.$anonfun$run$9(CoarseGrainedExecutorBackend.scala:477)
	at scala.runtime.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.java:23)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:877)
	at scala.collection.immutable.Range.foreach(Range.scala:158)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:876)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.$anonfun$run$7(CoarseGrainedExecutorBackend.scala:475)
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:62)
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:61)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
	... 4 more
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [120 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:293)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	... 16 more
22/01/14 00:57:44 ERROR RpcOutboxMessage: Ask terminated before connecting successfully
22/01/14 00:57:44 WARN NettyRpcEnv: Ignored failure: java.io.IOException: Connecting to spark-00000002vim192ao4dv-06b24e7e560b1279-driver-svc.spark.svc/10.99.80.100:7078 timed out (120000 ms)
Heap
 par new generation   total 306688K, used 256379K [0x0000000080000000, 0x0000000094cc0000, 0x0000000094cc0000)
  eden space 272640K,  94% used [0x0000000080000000, 0x000000008fa5ec40, 0x0000000090a40000)
  from space 34048K,   0% used [0x0000000090a40000, 0x0000000090a40000, 0x0000000092b80000)
  to   space 34048K,   0% used [0x0000000092b80000, 0x0000000092b80000, 0x0000000094cc0000)
 concurrent mark-sweep generation total 1756416K, used 0K [0x0000000094cc0000, 0x0000000100000000, 0x0000000100000000)
 Metaspace       used 22270K, capacity 23200K, committed 23288K, reserved 1069056K
  class space    used 3131K, capacity 3268K, committed 3352K, reserved 1048576K
```

**driver log**
```
22/01/14 00:57:45 INFO ExecutorPodsAllocator: Going to request 1 executors from Kubernetes for ResourceProfile Id: 0, target: 2 running: 1.
22/01/14 00:57:45 INFO KubernetesClientUtils: Spark configuration files loaded from Some(/usr/lib/spark/conf) : log4j.properties,spark-env.sh,hive-site.xml,metrics.properties
22/01/14 00:57:45 INFO BasicExecutorFeatureStep: Decommissioning not enabled, skipping shutdown script
22/01/14 00:57:46 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
22/01/14 00:58:01 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
22/01/14 00:58:16 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
22/01/14 00:58:29 INFO ExecutorPodsAllocator: Going to request 1 executors from Kubernetes for ResourceProfile Id: 0, target: 2 running: 1.
22/01/14 00:58:29 INFO KubernetesClientUtils: Spark configuration files loaded from Some(/usr/lib/spark/conf) : log4j.properties,spark-env.sh,hive-site.xml,metrics.properties
22/01/14 00:58:29 INFO BasicExecutorFeatureStep: Decommissioning not enabled, skipping shutdown script
22/01/14 00:58:31 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
22/01/14 00:58:46 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
22/01/14 00:59:01 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
22/01/14 00:59:16 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
22/01/14 00:59:31 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
```

## Describe the solution you'd like.

Possibly update ingress/egress rules in https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/node_groups.tf#L21

I just made a hotfix change, which is similar to the following. It works but may be too generous.

```
node_security_group_rules = {
...
    ingress_self = {
      description                   = "Node groups ingress self"
      protocol                       = "-1"
      from_port                     = 0
      to_port                         = 0
      type                              = "ingress"
      source_cluster_security_group = true
    }
    egress_all = {
      description = "Outbound all"
     cidr_blocks = ["0.0.0.0/0"]
      protocol    = "-1"
      from_port   = 0
      to_port     = 0
      type        = "egress"
    }
...
}
```

**Comment by daroga0002** [comment]
Module itself creating limited security groups to enforce a security standards. About security groups you can read here https://github.com/terraform-aws-modules/terraform-aws-eks#security-groups



Offcourse you can always extend or add additional SGs as per your need using this module.

**Comment by bryantbiggs** [comment]
exactly as @daroga0002 stated - the bare minimum access is provided to bring up a cluster, but its up to users to extend to suite their workload. its easier to expand the access/connectivity footprint than it is to contract/restrict it

**Comment by jaehyeon-kim** [comment]
For those who find a way to update security groups for EMR, here is what I did by adding additional rules. I initially added those rules to `eks_managed_node_group_default.security_group_rules` but that doesn't seem to be a good place as it doesn't update them for self managed node group or fargate profile. 

The individual rules are too generous and they'd have to be restricted.

```
  node_security_group_additional_rules = {
    ingress_all_cluster_node = {
      description  = "Allow all traffic from cluster node sg group for EMR"
      protocol      = "-1"
      from_port    = 0
      to_port        = 0
      type             = "ingress"
      self               = true
    }
    egress_all = {
      description  = "Outbound all for EMR"
      protocol      = "-1"
      from_port    = 0
      to_port        = 0
      type             = "egress"
      cidr_blocks = ["0.0.0.0/0"]
    }
  }
```

Also this module doesn't support to configure EMR on EKS. You may find this one useful - https://github.com/aws-samples/aws-eks-accelerator-for-terraform/blob/main/modules/emr-on-eks/main.tf
